version: '3.9'

services:
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility

  agent:
    build: .
    container_name: langchain-agent
    depends_on:
      - ollama
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - app/.env
    volumes:
      - ./app:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000

volumes:
  ollama:
